generate_module_outline:
  agent: instructional_architect
  output_file: output/module-outline.md
  description: >
    As the Senior Instructional Architect, your primary task is to generate a 
    detailed module outline for a technical (with coding) or non-technical 
    module. This includes creating sections for the instructor overview and 
    agenda, learner persona and prerequisites, and individual microlesson
    structures (title, learning objective, and an overview of the microlesson's 
    content).

    Your process should involve the following steps, informed by the provided 
    module topic, learner persona, and learning objectives as follows:

    The module topic is: {module_topic} 
    
    The learner persona is: {learner_persona}

    The learning objectives are: {learning_objectives}

    1.  Define Module Title: Use the provided title: {module_title}.

    2.  Analyze Inputs and Infer Context:
        Review the provided module topic, learner persona, and any 
        learning_objectives. From these, infer:
        - Appropriate technical or domain prerequisites.
        - Learner motivations, goals, and challenges.
        - Real-world contexts and examples relevant to the topic.

    3.  Design Microlesson Structure:
        Determine the number and sequence of microlessons based on number of 
        learning_objectives provided. For each microlesson:
        - Create a concise title.
        - Outline key theoretical concepts to be introduced.
        - Include a method for learners to check their understanding (e.g., a 
          multiple-choice question, coding prompt, or reflection).

    4.  Populate the Outline with Clear, Industry-Relevant Content:
        For each microlesson, provide a detailed overview of the key topics to 
        be covered. These topics should be:
        - Directly aligned with the microlesson’s learning objective.
        - Drawn from current industry practices, tools, and knowledge.
        - Selected to build progressively toward the overall module goal.
        - Use descriptive subsection names that reflect the actual content 
          (e.g., “Model Evaluation Metrics” or “Using Git Branches”), rather 
          than generic structural labels like "Theory".
        - Include estimated time durations for each microlesson. These 
          estimates should reflect realistic pacing for remote or hybrid 
          delivery, keeping {learner_persona} in mind, including time for 
          guided practice and learner interaction.
        - Ensure each microlesson balances conceptual understanding and 
          practical application, tied clearly to industry-relevant skills and 
          tasks.

    5.  Embed Best Practices:
        Ensure alignment with GA's adult learning theory as outlined in 
        "general_assembly_learning_philosophy" and curriculum design best 
        practices including:
        - Keep theory concise and actionable.
        - Make activities highly relevant and tool-aligned with {tools}.
        - Ensure accessibility for remote learners.

  expected_output: >
    A comprehensive module outline in Markdown format, structured according to 
    the following:

    - **Instructor overview and agenda:**
      - Overview: A brief summary of the module's purpose and structure.
      - Agenda: A list of **generated** microlesson titles. Include the estimated time it will take to complete each microlesson in "[ ]".
      - Required Tools: List of necessary software as defined in {tools}.
    - **Learner Persona and Prerequisites:**
      - Learner Persona: A description of the target audience (using the 
        provided {learner_persona}).
      - Prerequisites: A list of required skills or knowledge (based on 
        {module_topic} and {learner_persona}).
    - **Learning Objectives and Outcomes:**
      - High-Level Learning Goal: A sentence stating the module's main purpose 
        (generated based on {module_topic}).
      - Learning Objectives: A bulleted list of provided {learning_objectives}
    - **Microlessons:**
      - For each microlesson:
        - Title: Include the title and add the estimated time in "[ ]". For 
          example : "Introduction to APIs [15 min]"
        - Learning Objective
        - Outline: A brief outline of the key concepts that will be covered in 
          the microlesson.
