generate_module_outline:
  agent: instructional_architect
  output_file: output/module-outline.json
  description: >
    As the Senior Instructional Architect, your primary task is to generate a 
    detailed module outline for a technical (with coding) or non-technical 
    module. This includes creating sections for the instructor overview and 
    agenda, learner persona and prerequisites, and individual microlesson
    structures (title, learning objective, and an overview of the microlesson's 
    content).

    Your process should involve the following steps, informed by the provided 
    module topic, learner persona, how many minutes the module is,and learning 
    objectives as follows:

    The module topic is: {module_topic} 
    
    The learner persona is: {learner_persona}

    The learning objectives are: {learning_objectives}

    The module is {module_minutes} minutes long.

    1.  Define Module Title: Use the provided title: {module_title}.

    2.  Analyze Inputs and Infer Context:
        Review the provided module topic, learner persona, and any 
        learning objectives. From these, infer:
        - Appropriate technical or domain prerequisites.
        - Learner motivations, goals, and challenges.
        - Real-world contexts and examples relevant to the topic.

    3.  Design Microlesson Structure:
        Determine the number and sequence of microlessons based on number of 
        learning objectives provided. For each microlesson:
        - Create a concise title.
        - Outline key theoretical concepts to be introduced.
        - Include a method for learners to check their understanding (e.g., a 
          multiple-choice question, coding prompt, or reflection).
        - Include estimated time durations for each microlesson. These
          should reflect realistic pacing for remote or hybrid delivery, 
          keeping {learner_persona} in mind, including time for guided practice 
          and learner interaction.

    4.  Populate the Outline with Clear, Industry-Relevant Content:
        For each microlesson, provide a detailed overview of the key topics to 
        be covered. These topics should be:
        - Directly aligned with the microlesson’s learning objective.
        - Drawn from current industry practices, tools, and knowledge.
        - Selected to build progressively toward the overall module goal.
        - Use descriptive subsection names that reflect the actual content 
          (e.g., “Model Evaluation Metrics” or “Using Git Branches”), rather 
          than generic structural labels like "Theory".
        - Include estimated time durations for each microlesson. These 
          estimates should reflect realistic pacing for remote or hybrid 
          delivery, keeping {learner_persona} in mind, including time for 
          guided practice and learner interaction.
        - Ensure each microlesson balances conceptual understanding and 
          practical application, tied clearly to industry-relevant skills and 
          tasks.
        - When creating the microlesson outline, make sure you're taking the duration of the microlesson into account. 

    5.  Embed Best Practices:
        Ensure alignment with GA's adult learning theory as outlined in 
        "general_assembly_learning_philosophy" and curriculum design best 
        practices including:
        - Keep theory concise and actionable.
        - Make activities highly relevant and tool-aligned with {tools}.
        - Ensure accessibility for remote learners.

  expected_output: >
    A comprehensive module outline in JSON format, structured according to 
    the following:

    - `overview`: A brief summary of the module's purpose and structure (generated based on {module_topic}).
    - `tools`: List of necessary software as defined in {tools}.
    - `learnerPersona`: A description of the target audience (using the 
      provided {learner_persona}).
    - `prerequisites`: A list of required skills or knowledge (based on 
        {module_topic} and {learner_persona}).
    - Microlessons array:
      - For each microlesson:
        - `title`: Include the title of the microlesson. 
        - `time`: Include the estimated time it will take to complete the microlesson in minutes.
        - `learningObjective`: The exact learning objective for the microlesson as provided in the {learning_objectives}.
        - `outline`: A brief outline of the key concepts that will be covered 
          in the microlesson.
