learning_design_task:
  agent: learning_experience_designer
  output_file: output/learning-design-ml-{id}-{slug}.md
  description: >
    As the Learning Experience Designer, your task is to take the concise 
    technical content developed by the subject matter expert and enrich it to 
    create a more relatable and impactful learning experience for the learner. 
    Drawing upon your expertise in instructional design and the provided 
    resources, you will layer in narrative elements, relatable moments, and 
    practical learning opportunities. In this task you will use the following 
    information to iterate on the content provided by the subject matter expert:

    This microlesson is a part of the module: {module_title}.
    The module is about: {module_topic}.

    The microlesson metadata is as follows:
    - Title: {title}
    - Time: {time}
    - Learning Objective: {learningObjective}
    - Learner Persona: {learner_persona}
    - Tools: {tools}
    
    For each microlesson, you must:

    1.  **Weave in narrative and relatable scenarios if appropriate:** Identify 
        key concepts and explore opportunities to introduce brief stories, 
        real-world examples, or analogies that resonate with the learner 
        persona's background and interests. These narratives should serve to 
        illustrate complex ideas in an accessible and memorable way, as guided 
        by `modular-writing.txt` and the tone defined in `technical-voice.txt`.

    2.  **Create connections through relatability and build on previous 
        content:** Analyze the technical content for potential points of 
        confusion or abstraction. Develop relatable examples or analogies that 
        bridge the gap between the abstract and the concrete, helping learners 
        grasp the underlying principles. Refer to 
        `creating-clear-exercises.txt` for guidance on building effective and 
        understandable examples.

    3.  **Strategically incorporate interaction:** Review the existing activity 
        and identify natural points to embed meaningful interactions and 
        knowledge checks (discussion prompts, chat questions). Ensure these 
        interactions are purposeful, reinforce the learning objectives, and 
        cater to the learner persona's engagement style.

    4.  **Optimize for practical application:** Consider how the existing 
        theoretical content can be directly connected to practical application 
        and real-world problem-solving. Suggest ways to modify activities or 
        add mini-challenges that allow learners to apply their knowledge in 
        realistic scenarios, potentially leveraging the capabilities of 
        the tools used in the microlesson as described in `modular-code.txt` 
        for technical topics.

    5.  **Maintain learning focus:** Ensure that all added narrative elements, 
        relatable moments, and interactive opportunities directly support the 
        learning objectives of the microlesson and contribute to a deeper
        understanding of the core concepts. Never add elements that are purely 
        for entertainment and do not serve a pedagogical purpose.

    6.  **Format for clarity and connection:** Ensure the final output adheres 
        to the formatting guidelines in `markdown-document-structure.txt`, 
        making the content visually appealing and easy to follow. Use 
        formatting to highlight relatable examples and key takeaways.

    7.  **IMPORTANT - Craft globally relevant content:** Ensure that the 
        content is relevant to a global audience. Avoid using american-centric 
        examples or references that may not resonate with learners from 
        different cultural backgrounds. Use examples that are universally 
        relatable and applicable to a diverse audience. Refrain from using 
        idioms or colloquial expressions that may not translate well across 
        cultures. Use the 
        `creating-inclusive-and-globally-relevant-content.txt` document to help 
        with this.

    8.  **IMPORTANT - The final output should sound like a human wrote it, 
        not a computer.**

    9.  **The SME has created the below content for this microlesson. 
        You must use this content as a starting point and build upon it:**

        {sme_content}

    10. **Take into account the previous microlessons in the module as you're 
        developing this microlesson. Here is the content from the previous 
        microlessons:**
        {microlessons_ld_text}

  expected_output: >
    An Markdown document that builds upon the content provided by the subject 
    matter expert. This document should feature a more narrative flow, clearly 
    highlighted relatable examples and analogies, strategically placed 
    interactive elements, and a strong emphasis on practical application. The 
    output should include:

    - The title of the microlesson - do not change the title from the subject 
      matter expert's content.
    - The learning objective of the microlesson - do not change the title from 
      the subject matter expert's content.
    - Explanations tailored to the learner persona, defining jargon or 
      simplifying complex terms.
    - Do not change any headings from the subject matter expert's content.

    Formatting: Consistent and effective use of Markdown formatting as per 
    `markdown-document-structure.txt` and `modular-code.txt` to enhance 
    clarity and connection.

    The final output should represent a learning experience that is not only 
    informative, but also relatable, engaging, and clearly demonstrates the 
    practical application of the module topic for the learner persona, 
    ultimately leading to deeper understanding and retention.
