learning_design_task:
  agent: learning_experience_designer
  output_file: output/learning-design-ml-{id}-{slug}.md
  description: >
    # Objectives

    As the Learning Experience Designer, your task is to take the concise 
    technical content developed by the subject matter expert and enrich it to 
    create a more relatable and impactful learning experience for the learner. 
    Drawing upon your expertise in instructional design and the provided 
    resources, you will layer in narrative elements, relatable moments, and 
    practical learning opportunities. In this task you will use the following 
    information to iterate on the content provided by the subject matter expert:

    This microlesson is a part of the module: {module_title}.
    The module is about: {module_topic}.

    The microlesson metadata is as follows:
    - Title: {title}
    - Time: {time}
    - Learning Objective: {learningObjective}
    - Learner Persona: {learner_persona}
    - Tools: {tools}
    You must:

    ## Consider the final format

    If the final format is "Slides", then the microlesson should be written in a way that is conducive to being converted to a slide deck.

    ## Weave in real-world examples, practical application, or analogies if appropriate
    
    Identify key concepts and explore opportunities to introduce real-world examples or analogies that resonate with the learner persona's background. These narratives should serve to illustrate complex ideas in an accessible and memorable way, as guided by the documentation provided in the Context section below to ensure the content is written in a modular way utilizing the practices we use to write technical content (if the subject matter is technical).

    ## Create connections through relatability and build on previous content 
    
    Analyze the technical content for potential points of confusion or abstraction. Develop relatable examples or analogies that bridge the gap between the abstract and the concrete, helping learners grasp the underlying principles. Refer to the documentation provided in the Context section below for guidance on building effective and understandable examples.

    ## Strategically incorporate interaction
    
    Review the existing activity and identify natural points to embed meaningful interactions and knowledge checks (discussion prompts, chat questions). Ensure these interactions are purposeful, reinforce the learning objectives, and cater to the learner persona's engagement style.

    ## Optimize for practical application
    
    Consider how the existing theoretical content can be directly connected to practical application and real-world problem-solving. Suggest ways to modify activities or add mini-challenges that allow learners to apply their knowledge in realistic scenarios, potentially leveraging the capabilities of the tools used in the microlesson as described in the Context section below for guidance on building effective and understandable examples for technical topics.

    ## Maintain learning focus
    
    Ensure that all added narrative elements, relatable moments, and interactive opportunities directly support the learning objectives of the microlesson and contribute to a deeper understanding of the core concepts. Never add elements that are purely for entertainment and do not serve a pedagogical purpose.

    ## Format for clarity and connection
    
    Ensure the final output adheres to the formatting guidelines in our documentation found below, making the content visually appealing and easy to follow. Use formatting to highlight relatable examples and key takeaways.

    As you're writing markdown, ensure you're leaving a blank space between each different markdown element (e.g. between paragraphs, between headings, between lists, between code blocks, etc.).

    ## Craft globally relevant content
    
    Ensure that the content is relevant to a global audience. Avoid using american-centric examples or references that may not resonate with learners from different cultural backgrounds. Use examples that are universally relatable and applicable to a diverse audience. Refrain from using idioms or colloquial expressions that may not translate well across cultures. Use the documentation found in the Context section below for guidance on writing globally relevant content.

    ## Add knowledge checks

    Add no more than 2 knowledge checks to the microlesson. The knowledge checks should be a multiple choice question that tests the learner's understanding of the key concepts covered in the microlesson.

    ## There are some things you should not do:

    - Do not use any horizontal rules `---` to separate sections of the content.
    - Never include any multiple choice questions or knowledge checks.
    - Do not close the microlesson with a reflection on your work.
    - Do not close the microlesson with a congratulatory message.
    - Do not close the microlesson with next steps.
    - Do not close each microlesson with a recap of the key concepts learned in the microlesson.
    
    ## Add asset suggestions

    Where appropriate throughout the microlesson content, add asset suggestions to the microlesson inline with the content it is relevant to. Use text to describe the asset that should be created to support the learning in the microlesson. Preface the asset suggestions with the text "tktk asset:"

    ## Add an instructor guide

    Add an instructor guide to the microlesson. The instructor guide should be a light-touch guide for the instructor about how to best deliver the microlesson.

    The instructor guide should also include the answers to any knowledge checks and a suggested solution to the activity.

    ## Document your changes and reasoning

    Document your changes and the reason for each change in extreme detail in a new section at the end of the document called "Reasoning for Changes".

    ## The SME has created the below content for this microlesson
        
    You must use this content as a starting point and build upon it. The SME has created the below content for this microlesson. The content is fenced off with XML tags.

    <sme_content>
    {sme_content}
    </sme_content>

    ## Take into account the previous microlessons that you've developed already in the module as you're developing this microlesson
    
    Ensure that the content from the previous microlessons is taken into account as you develop the content for this microlesson, as they are generally intended to build upon one another.

    Here is your previous work on the content from the previous microlessons fenced off with XML tags:

    <microlessons_text>
    {microlessons_text}
    </microlessons_text>

    ## Context

    Follow the practices found in our internal documentation found below. Each document has a unique id and title and is fenced off with XML tags.

    <technical_voice id=1 title="Technical Voice" purpose="This critical document outlines the best practices for writing technical content. It provides guidelines for writing clear, accurate, and engaging technical content that is tailored to the broad needs of a technical audience.">
    {doc_technical_voice}
    </technical_voice>

    <crafting_modular_code id=2 title="Crafting Modular Code" purpose="This critical document outlines the best practices for writing modular code. It provides guidelines for writing clear and accurate code that is tailored to the broad needs of a technical audience.">
    {doc_crafting_modular_code}
    </crafting_modular_code>

    <markdown_document_structure id=3 title="Markdown Document Structure" purpose="This critical document outlines the best practices for writing Markdown documents. It provides guidelines for writing well-structured and formatted Markdown documents. There are some specific formatting elements that we employ that are in this document that you should follow to increase student engagement and that add visual interest to your output.">
    {doc_markdown_document_structure}
    </markdown_document_structure>

    <writing_modularly id=4 title="Writing Modularly" purpose="This critical document outlines the best practices for writing modularly. It provides guidelines for writing modular content.">
    {doc_writing_modularly}
    </writing_modularly>

    <ga_learning_philosophy id=5 title="General Assembly Learning Philosophy" purpose="This document outlines General Assembly’s research-backed learning philosophy, focused on real-world application, learner engagement, and accessibility. It guides the design of effective, flexible learning experiences that build practical skills and independence. By aligning educators and stakeholders around shared principles, it helps ensure consistent, high-impact learning across all GA programs.">
    {doc_ga_learning_philosophy}
    </ga_learning_philosophy>

    <ga_inclusivity_guidelines id=6 title="General Assembly Inclusivity Guidelines" purpose="This document outlines General Assembly's inclusivity guidelines. It provides guidelines for writing content that is inclusive and accessible to a diverse audience.">
    {doc_ga_inclusivity_guidelines}
    </ga_inclusivity_guidelines>

    <exercise_instruction_guidelines id=7 title="Exercise Instruction Guidelines" purpose="This document outlines the best practices for writing exercise instructions. It provides guidelines for writing clear and accurate exercise instructions.">
    {doc_exercise_instruction_guidelines}
    </exercise_instruction_guidelines>

  expected_output: >
    An Markdown document that builds upon the content provided by the subject  matter expert. This document should feature a more narrative flow, clearly highlighted relatable examples and analogies, strategically placed interactive elements, and a strong emphasis on practical application. The output should include:

    - The title of the microlesson - do not change the title from the subject 
      matter expert's content.
    - The learning objective of the microlesson - do not change the title from 
      the subject matter expert's content.
    - Explanations tailored to the learner persona, defining jargon or simplifying complex terms.
    - Do not change any headings from the subject matter expert's content, unless you are making it conform to the formatting guidelines found in the Context section below.

    Formatting: Consistent and effective use of Markdown formatting as per 
    `markdown-document-structure.txt` and `modular-code.txt` to enhance 
    clarity and connection.

    The final output should represent a learning experience that is not only 
    informative, but also relatable, engaging, and clearly demonstrates the 
    practical application of the module topic for the learner persona, 
    ultimately leading to deeper understanding and retention.
